// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-FckyrCyO3tyFEFroQ9CDAYmgFGegMfA',
    appId: '1:441448234304:web:14a244f5a986c64b344ea5',
    messagingSenderId: '441448234304',
    projectId: 'learn-firebase-dd4fe',
    authDomain: 'learn-firebase-dd4fe.firebaseapp.com',
    storageBucket: 'learn-firebase-dd4fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU271SQl2e9Bhy3FWfVXLyVQiOBKaRD8Y',
    appId: '1:441448234304:android:362144fffec048fc344ea5',
    messagingSenderId: '441448234304',
    projectId: 'learn-firebase-dd4fe',
    storageBucket: 'learn-firebase-dd4fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIIE6GkBIr4phFZa68D2-TUIHukYt9Jc',
    appId: '1:441448234304:ios:348e772c1b81c1f5344ea5',
    messagingSenderId: '441448234304',
    projectId: 'learn-firebase-dd4fe',
    storageBucket: 'learn-firebase-dd4fe.appspot.com',
    iosClientId: '441448234304-s6t8qv2fcs95iqhpt02l6qm3vv69us9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIIE6GkBIr4phFZa68D2-TUIHukYt9Jc',
    appId: '1:441448234304:ios:348e772c1b81c1f5344ea5',
    messagingSenderId: '441448234304',
    projectId: 'learn-firebase-dd4fe',
    storageBucket: 'learn-firebase-dd4fe.appspot.com',
    iosClientId: '441448234304-s6t8qv2fcs95iqhpt02l6qm3vv69us9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLearn',
  );
}
